### ISSUE TITLE
File type

### ISSUE THREAD

**Issue by Behzadkha** [myrithok/James#13]
The app freezes after uploading a DOCX file (something other than txt).
**Environment**
Windows desktop,
Browser: Chrome

**Steps to reproduce**
Upload a DOCX file.

**Expected result**
Get a pop up message saying that only txt file is acceptable.
**Actual result**
The app crashes.
**Screenshot**
![JamesUploadType](https://user-images.githubusercontent.com/24414425/109082541-363b5580-76d2-11eb-8a59-dccf98509777.PNG)

**Severity**
HIGH

**Comment by Warbler-tweet** [comment]
will fix on front end

**Comment by robertjvardy** [comment]
fixed by: 5336d88cb432f0e32eaeb4db59cababf63e1c657
