### ISSUE TITLE
Number of topics input error

### ISSUE THREAD

**Issue by Behzadkha** [myrithok/James#14]
The app is stuck on loading when you enter a number as the number of topics
I tried different numbers. 22, 1000, 100000000. All crashed the app.
**Environment**
Windows desktop,
Browser: Chrome

**Steps to reproduce**
Enter 100 as the Number Of Topics

**Expected result**
Show 100 topics
**Actual result**
The app crashes.
**Screenshot**
![InputError](https://user-images.githubusercontent.com/24414425/109083024-18222500-76d3-11eb-90ec-7d98a4c3e379.PNG)
![InputError2](https://user-images.githubusercontent.com/24414425/109083031-19535200-76d3-11eb-9007-3d466887276d.PNG)

**Severity**
HIGH

**Comment by Warbler-tweet** [comment]
will fix on front end. number of topic limits.

**Comment by robertjvardy** [comment]
fixed on commit: aad4edac374016d2c0e70d6d523fcdc8a3bdccee
