### ISSUE TITLE
Topics: Negative Number

### ISSUE THREAD

**Issue by Behzadkha** [myrithok/James#15]
The app crashes if a negative number is entered for Number of Topics
**Environment**
Windows desktop,
Browser: Chrome

**Steps to reproduce**
Enter a negative number as Number of Topics.

**Expected result**
Get a pop up message saying that negative number is not allowed.
**Actual result**
The app crashes.
**Screenshot**
![negativenumber](https://user-images.githubusercontent.com/24414425/109083374-ccbc4680-76d3-11eb-9ca0-524015c44121.PNG)
![negativeNumberCrash](https://user-images.githubusercontent.com/24414425/109083379-ce860a00-76d3-11eb-848d-803a5ad129d7.PNG)

**Severity**
HIGH

**Comment by Warbler-tweet** [comment]
will fix on front end. conditional check integer is non-negative

**Comment by robertjvardy** [comment]
fixed on commit: aad4edac374016d2c0e70d6d523fcdc8a3bdccee
