### ISSUE TITLE
Users can't upload multiple files from different folders, or upload multiple txt files by drag and dropping them one at a time.

### ISSUE THREAD

**Issue by Behzadkha** [myrithok/James#16]
If two txt files are in folder A and one txt file is in folder B, then you can't upload all three of them because if you upload one at a time, the previously uploaded files will be deleted (tried drag-drop and clicking on the upload button to browse the file).
In the screen-shot below, if you upload a txt file called "test1.txt", the current "test2.txt" file gets deleted(just disappears) so if there are two files uploaded, user can't upload a third file.

**Environment**
Windows desktop,
Browser: Chrome

**Steps to reproduce**
Select two txt files from your desktop and drag them to the app to upload them. It is going to show the uploaded files perfectly fine but you will lose those txt files when you upload a third file.

**Expected result**
User should be able to upload txt files one at a time. The app should keep all of them.
**Actual result**
You lose your previous uploaded file when you upload a new file.
**Screenshot**
![twofiles](https://user-images.githubusercontent.com/24414425/109083954-ddb98780-76d4-11eb-90f7-1502935001bc.PNG)

**Severity**
MEDIUM

**Comment by Warbler-tweet** [comment]
will fix on front end. previously dropped files are overwritten.

**Comment by myrithok** [comment]
Thank you for the feedback! The file uploader is working as intended, but this behaviour is certainly confusing when the user is not given any instructions. We've added instructions, including a warning about this behaviour, in commit 00267355b8d719f8c699641861c2a13ecda95c08
