### ISSUE TITLE
LOW - UI is not responsive

### ISSUE THREAD

**Issue by Behzadkha** [myrithok/James#17]
The text in the upload(drag-drop) button is chopped.
If you view the app in a smaller screen, the texts are not readable. 

**Environment**
Windows desktop,
Browser: Chrome

**Steps to reproduce**
Press Ctrl + Shift + i to inspect. Change the windows size to 411 x 823

**Expected result**
Be able to see the upload text even when the screen is small.
**Actual result**
Some texts are not readable in a smaller screen. 
**Screenshot**
![image](https://user-images.githubusercontent.com/24414425/109093517-815f6380-76e6-11eb-9798-0454a3b66695.png)

**Severity**
MEDIUM

**Comment by Warbler-tweet** [comment]
seen.

**Comment by robertjvardy** [comment]
fixed with: 398a3177921178a89a41eede022113ae0a1c666d
