### ISSUE TITLE
LOW - There should be a space between : and input

### ISSUE THREAD

**Issue by Behzadkha** [myrithok/James#18]
**Environment**
Windows desktop,
Browser: Chrome

**Steps to reproduce**
There should be a space between : and text.

**Expected result**
Number of Topics: `<input>`
**Actual result**
Number of Topics:`<input>`
**Screenshot**
![image](https://user-images.githubusercontent.com/24414425/109094730-773e6480-76e8-11eb-9c47-27f40acc39cc.png)

**Severity**
MEDIUM

**Comment by myrithok** [comment]
Thank you! Fixed in commit b415ebd5b7ed90c05a98a577741f0e0939c27020
github.com/myrithok/James/commit/b415ebd5b7ed90c05a98a577741f0e0939c27020
