### ISSUE TITLE
App hangs on analyzing empty text file

### ISSUE THREAD

**Issue by Gregory-Kitching** [myrithok/James#19]
Submitting an empty text file causes the app to hang, with no indication as to what the app is doing or whether it is even still running.

![Screenshot from 2021-02-25 15-24-00](https://user-images.githubusercontent.com/79662360/109213139-40b32900-777e-11eb-8111-91bd33129d0b.png)
I waited for about five minutes, but the app did not produce output.

![Screenshot from 2021-02-25 15-24-21](https://user-images.githubusercontent.com/79662360/109213146-427cec80-777e-11eb-83f9-27226a962d7a.png)
The file that was uploaded.

**Comment by eaharis** [comment]
Fixed: c6f512ce1904f804fa096c917e61ad7b505c138d
