### ISSUE TITLE
App hangs on analyzing single character

### ISSUE THREAD

**Issue by Gregory-Kitching** [myrithok/James#20]
Uploaded a text file consisting only of the letter "a". After five minutes the app did not produce output, much like issue #19.

![Screenshot from 2021-02-25 15-24-00](https://user-images.githubusercontent.com/79662360/109214447-d7341a00-777f-11eb-98c9-9b8e68e99238.png)

![Screenshot from 2021-02-25 15-38-45](https://user-images.githubusercontent.com/79662360/109214457-db603780-777f-11eb-9375-c69a6acb3424.png)

**Comment by eaharis** [comment]
Fixed: c6f512ce1904f804fa096c917e61ad7b505c138d
