### ISSUE TITLE
Zero Topics Selected Freezes Loading

### ISSUE THREAD

**Issue by trevorNgo** [myrithok/James#21]
Medium Severity

When selecting 0 topics, the app will infinitely load or not respond.

Expected behavior:
The app will choose "default" value or will display an input error. App should not continue to proceed with the analysis process.

Repro:
Select by pressing up and down arrow, or type in 0 into input box for "Number of Topics". 
Upload a valid text file.
Click calculate.

The image below shows two browser windows opened simultaneously, where in the left window instance, 0 topics were selected and the other the default empty input was used.

![image](https://user-images.githubusercontent.com/23327878/109322344-30ec2100-7820-11eb-9a06-a40d734c1f21.png)

**Comment by robertjvardy** [comment]
fixed on commit: aad4edac374016d2c0e70d6d523fcdc8a3bdccee
