### ISSUE TITLE
Inputting Text File With Missing File Extension

### ISSUE THREAD

**Issue by trevorNgo** [myrithok/James#22]
Severity: Low

Repro steps:
By removing the .txt file extension (via file rename) and uploading this to the app, it will hang on the loading icon.

Expected behavior:
For Robust behavior: will attempt to read the file stream binaries of the unlabeled txt file first. After verifying it is an incompatible file type will it let the user know their file type is not acceptable.

![image](https://user-images.githubusercontent.com/23327878/109327032-deadfe80-7825-11eb-92f8-f5cfbcc6639e.png)

**Comment by robertjvardy** [comment]
fixed by: 5336d88cb432f0e32eaeb4db59cababf63e1c657
