### ISSUE TITLE
Upload Button Remains Interactive

### ISSUE THREAD

**Issue by trevorNgo** [myrithok/James#23]
Severity: Low

After uploading a file and waiting for "the algorithm" to compute, the upload buttons remains interactive.

Expected behavior:
This button should be disabled.

![image](https://user-images.githubusercontent.com/23327878/109324811-2e3efb00-7823-11eb-937f-0e9a9feec91a.png)

**Comment by robertjvardy** [comment]
fixed on: 02a77ee263f8adc4f9184cc697292cd639a42f6d
