### ISSUE TITLE
Results Page Not Responsive And Breaks On Any Orientation Change

### ISSUE THREAD

**Issue by trevorNgo** [myrithok/James#24]
Severity Medium
Reproduction steps:
Resize the browser window; use chrome mobile emulation tool or use a mobile device to access the app.

When viewing the results page on a reduced width window size or on any mobile orientation, the results are unreadable and the container splits into two columns that run vertically when the mobile orientation changes.

![image](https://user-images.githubusercontent.com/23327878/109325265-b6bd9b80-7823-11eb-9112-cbee0e1af458.png)

When viewing on emulated mobile page, and changing orientation to landscape, the container holding the results get split into two laid vertically next to each other.
Landscape to Portrait:
![image](https://user-images.githubusercontent.com/23327878/109325518-08662600-7824-11eb-848a-8c482d4d0f76.png)

Portrait to landscape:
![image](https://user-images.githubusercontent.com/23327878/109326172-d43f3500-7824-11eb-85d4-67de1bbf2f05.png)

**Comment by robertjvardy** [comment]
fixed with: 3901c8c6beda7c860d5a83f9ba30ecf926c6dc90
