### ISSUE TITLE
Floats and Scientific Notation Permitted In the Input

### ISSUE THREAD

**Issue by trevorNgo** [myrithok/James#25]
Severity: high

Repro steps:
When inputting "Number of Topics", insert `5.012301e1213123` into input.

Expected behavior:
Input validation error thrown or restricting the input characters to non scientific notation.
![image](https://user-images.githubusercontent.com/23327878/109326875-b2927d80-7825-11eb-85a1-1f00343ddcf9.png)

**Comment by robertjvardy** [comment]
fixed by: d0a5bb9540723f17b08cec8ffd258b35a519fa0e
