### ISSUE TITLE
App fails on improper file formatting

### ISSUE THREAD

**Issue by elwazana** [myrithok/James#26]
**Severity** - Medium

**Description**
It seems that the app fails and hangs on any improperly formatted text files: I came to this conclusion due to the following error, a text file with the following contents: 
![image](https://user-images.githubusercontent.com/35268928/109357774-c901fe80-7850-11eb-9eb2-b6b6afe8fb74.png)
will stall: 
![image](https://user-images.githubusercontent.com/35268928/109357907-f77fd980-7850-11eb-85b1-fd742a8b0d9f.png)
Coupled with issues: #20 and #19. This is despite the UI text implying that any text file would work. 

**Environment**
Windows 10
Google Chrome

**Suggestion**
Have an example of proper/expected file formatting in the UI, an image of one would go a long way it at least explaining to the user why the app hangs on certain text files.

**Comment by eaharis** [comment]
Fixed: 77e18121a7ebf7c177b03443a12ecd95cc07ebc5
