### ISSUE TITLE
App fails ungracefully 

### ISSUE THREAD

**Issue by elwazana** [myrithok/James#27]
**Severity** - Low

**Description**
I've noticed by running my own tests and reading through the other posted issues that the app fails a lot by hanging or stalling. This stalling with no feedback from the system might frustrate user's from future use. This stalling seems to be a frequent occurrence with a large number of errors. 

**Suggestion**
Create a time limit proportional to the size of the upload to that app. Once the time limit is reached stop the app and have some pop-up explain to the user possible reasons for the stalling. This will not correct the cause of the system failing but will certainly improve the user's experience of the app.

**Comment by eaharis** [comment]
Fixed: 77e18121a7ebf7c177b03443a12ecd95cc07ebc5
