### ISSUE TITLE
Suggestion - should have a cancel button for the calculating

### ISSUE THREAD

**Issue by FangY2019** [myrithok/James#28]
If the user would like to stop the calculating for the current file, it is better to have a cancel button to cancel the current process and then the user can choose another file. 

## Environment

Device: ASUS Laptop
OS: Windows 10
Browser: Google Chrome

## Steps to Reproduce

1. Upload a text file
2. Click on Calculate
	
## Expected Result
User can cancel the calculation 

## Actual Result
User have to refresh the page to cancel the calculation

## Screenshot

![james1](https://user-images.githubusercontent.com/54195303/109985323-a2214d80-7cd2-11eb-9b46-febdccf568c7.PNG)

## Severity
LOW

**Comment by myrithok** [comment]
Thank you! We have added a cancel button in commit 009e635985ece91dc538b10197fefce81efc2e7b
