### ISSUE TITLE
[Design Issue] Provide Feedback when Users Must Wait

### ISSUE THREAD

**Issue by darrentu** [myrithok/James#30]
2.10 Provide Feedback when Users Must Wait
PAGE 40 in guidelines book

After uploading a text file with just the string "hello" in it, it hangs there (it's been over 30 minutes). 
Something worth trying is to have a progress bar for users to know how much longer they need to wait. 

Guidelines book: https://www.usability.gov/sites/default/files/documents/guidelines_book.pdf
*Note* This is for a school project.

**Comment by eaharis** [comment]
Fixed: 77e18121a7ebf7c177b03443a12ecd95cc07ebc5
