### ISSUE TITLE
[Design Issue] Highlight Critical Data

### ISSUE THREAD

**Issue by darrentu** [myrithok/James#31]
9.5 Highlight Critical Data
PAGE 105 in guidelines book

Try to highlight or bold the important parts of the description. I feel like most people won't bother reading the whole description. By bolding the important parts, you allow the users to more quickly find the important parts. 
For example, try bolding "LDA topic modelling" and potentially adding a hyperlink to a site that explains what it is. 

Guidelines book: https://www.usability.gov/sites/default/files/documents/guidelines_book.pdf
Note This is for a school project.

**Comment by myrithok** [comment]
Thank you for the suggestion! We've reworked the description, including clear and specific instructions, as well as links to detailed descriptions of techniques, in commit 00267355b8d719f8c699641861c2a13ecda95c08
