### ISSUE TITLE
500 Failed to load resource when non-text file is uploaded

### ISSUE THREAD

**Issue by sophiajwchoi** [myrithok/James#33]
## Expected Behavior
- When the user uploads a non-text file, the app should check the file type and return feedback to the user. 

## Actual Behavior
- The application hangs and returns Error: Request failed with status code 500.

## Steps to Reproduce the Problem

  1. Click the drop files button to select files.
  2. Select one text file and a non-text file (png)
  3. Check the console 

## Specifications

  - Platform: Windows 10 Chrome

**Comment by eaharis** [comment]
Fixed: c6f512ce1904f804fa096c917e61ad7b505c138d
