### ISSUE TITLE
After selecting a text file, I see Warning: Each child in a list should have a unique "key" prop. in the console

### ISSUE THREAD

**Issue by sophiajwchoi** [myrithok/James#34]
![image](https://user-images.githubusercontent.com/34407972/109881184-dc90d900-7c45-11eb-8b36-d192917afe59.png)

## Expected Behavior
- There shouldn't be any warning in the console when the file is selected

## Actual Behavior
- ![image](https://user-images.githubusercontent.com/34407972/109881184-dc90d900-7c45-11eb-8b36-d192917afe59.png)

## Steps to Reproduce the Problem

  1.  Select a text file by clicking the drop files icon
  2. Check the chrome console
  

## Specifications

  - Platform: Windows 10 chrome

**Comment by myrithok** [comment]
Thank you! Fixed in commit 358f4282a3e86ce777a8ba95233f3035a44c894c
