### ISSUE TITLE
Performance and response time issue NF-3-3-4

### ISSUE THREAD

**Issue by sophiajwchoi** [myrithok/James#37]
## Expected Behavior

One of the non-functional requirements was that a user will be able to understand and utilize the features in less than 5 minutes.
## Actual Behavior

when I upload a simple text file.
[a.txt](https://github.com/myrithok/James/files/6079624/a.txt)
The app does not return the results in less than 5 minutes. 

I received the following error in the chrome console.
Error: Request failed with status code 500
    at createError (createError.js:16)
    at settle (settle.js:17)
    at XMLHttpRequest.handleLoad (xhr.js:62)

## Steps to Reproduce the Problem

  1. Upload the above a.txt file

## Specifications

  - Platform: Windows 10 64 chrome

**Comment by Warbler-tweet** [comment]
The application now has clear instructions and suggestions on the web page.
