### ISSUE TITLE
Bad practice - hard coded IP

### ISSUE THREAD

**Issue by darrentu** [myrithok/James#39]
Try your best to avoid having hardcoded ip addresses. It's better to have a separate file for configuration

https://github.com/myrithok/James/blob/32ba2d125cd6dbef17a3de7f7a241e8ca8647ea2/ui/src/App.js#L58

Note - this is for a school project

**Comment by eaharis** [comment]
Fixed: c6f512ce1904f804fa096c917e61ad7b505c138d
