### ISSUE TITLE
[SEO issue] Keywords

### ISSUE THREAD

**Issue by darrentu** [myrithok/James#40]
If you care about optimizing your website for web crawlers, try to add in metadata keywords. https://www.w3schools.com/tags/tag_meta.asp

https://github.com/myrithok/James/blob/32ba2d125cd6dbef17a3de7f7a241e8ca8647ea2/ui/public/index.html#L6

Note - this is for a school project.

**Comment by myrithok** [comment]
Thank you for the suggestion! Added in commit 7f92b55ce04b8130726b474190cc2fd63a0cc9bf
