### ISSUE TITLE
Hidden output - formatting issues on results page

### ISSUE THREAD

**Issue by sophiajwchoi** [myrithok/James#41]
## Expected Behavior
- Results should be fully displayed to the user.

## Actual Behavior
- 
![image](https://user-images.githubusercontent.com/34407972/109918184-87c08300-7c84-11eb-9005-f9a8dd242695.png)

## Steps to Reproduce the Problem

  1. Upload a text file 
[alice.txt](https://github.com/myrithok/James/files/6081166/alice.txt)

  1. Click on Calculate
  1. Check the output

## Specifications

  - Platform: Chrome windows 10

**Comment by robertjvardy** [comment]
fixed with: 3901c8c6beda7c860d5a83f9ba30ecf926c6dc90
