### ISSUE TITLE
Uploading multiple text files fails

### ISSUE THREAD

**Issue by sophiajwchoi** [myrithok/James#42]
## Expected Behavior
- The app should handle multiple text files as inputs as described

## Actual Behavior
- The app hangs with an error code 500
- Error: Request failed with status code 500
    at createError (createError.js:16)
    at settle (settle.js:17)
    at XMLHttpRequest.handleLoad (xhr.js:62)

## Steps to Reproduce the Problem

  1. Upload 3 text files provided below
  1. Open up the chrome console

## Specifications

  - Platform: Chrome Windows 10
[t1.txt](https://github.com/myrithok/James/files/6081349/t1.txt)
[t3.txt](https://github.com/myrithok/James/files/6081350/t3.txt)
[t4.txt](https://github.com/myrithok/James/files/6081351/t4.txt)

**Comment by myrithok** [comment]
Thank you! We have actually been unable to replicate this issue. Most likely, whatever caused it was resolved in a commit that resolved another issue.

**Comment by myrithok** [comment]
Thank you! This issue was actually coming up because the input was too short. We've added instructions regarding input length, and correctly handled errors when input is too short.
