### ISSUE TITLE
Avoid global variables

### ISSUE THREAD

**Issue by darrentu** [myrithok/James#43]
If possible, always avoid global variables.

In the specific case of api/server.py, I don't believe you need the RESPONSE variable to be global.

https://github.com/myrithok/James/blob/32ba2d125cd6dbef17a3de7f7a241e8ca8647ea2/api/server.py#L20

Note - this is for a school project.

**Comment by myrithok** [comment]
Thank you! Fixed in commit 7c77e86fbb0c9e6e2e838461f50dd78832be5477
