### ISSUE TITLE
Ensure correct errors are shown if file upload fails

### ISSUE THREAD

**Issue by darrentu** [myrithok/James#44]
I took a look at the code in api/server.js. It's clear that on your server side, you have implemented responses to 'bad' scenarios (ex. File empty). However, it doesn't seem like your front end is showcasing those error messages to the user. Instead, I just get a spinner that keeps on spinning when I upload a file (for every single file I uploaded).

https://github.com/myrithok/James/blob/main/api/server.py

Note - this is for a school project

**Comment by eaharis** [comment]
Fixed: 4c49338a3518361d751dde109118a4986fe0f4f5
