### ISSUE TITLE
Weight and Sentiment values overlap 

### ISSUE THREAD

**Issue by Gabriel-Gebril** [myrithok/James#45]
When weight value had enough decimal places it will overlap with the sentiment value making it unreadable.

Environment: Windows, Google Chrome
Steps to Reproduce

- Upload this txt 
[SampleAnim_AddingFrames.txt](https://github.com/myrithok/James/files/6087415/SampleAnim_AddingFrames.txt)
- Click calculate
- Scroll down to the bottom
- Notice that the weigh value covers up the sentiment value

![image](https://user-images.githubusercontent.com/16761051/110028437-3acec200-7d01-11eb-983a-69981d9b2aa3.png)

**Comment by robertjvardy** [comment]
fixed with: 3901c8c6beda7c860d5a83f9ba30ecf926c6dc90
