### ISSUE TITLE
Unexpected back button behavior 

### ISSUE THREAD

**Issue by Gabriel-Gebril** [myrithok/James#46]
When pressing the back button from the results page you would expect to be returned to the upload page but instead you are returned to the page you were at before even opening the application.

Environment: Windows, Google Chrome
Steps to Reproduce

- Go from reddit.com to localhost:3000
- Upload a txt
- Go to report
- Click back button
- Notice how you are now on reddit.com again

**Comment by myrithok** [comment]
Thank you for the feedback! We have actually designed our web app to operate on a single dynamic webpage, so this behaviour is intended.
