### ISSUE TITLE
Strings containing emojis hang the applicaiton

### ISSUE THREAD

**Issue by Gabriel-Gebril** [myrithok/James#47]
"Hello 🤗" in the txt gave the application a hug of death. Probably a Unicode issue.

Environment: Windows, Google Chrome
Steps to Reproduce

- Upload a txt with an emoji in it (e.g. 🤗)
- Wait forever

**Comment by eaharis** [comment]
Fixed: 77e18121a7ebf7c177b03443a12ecd95cc07ebc5
