### ISSUE TITLE
Can continue to upload files even after clicking calculate.

### ISSUE THREAD

**Issue by Gabriel-Gebril** [myrithok/James#48]
You can continue to upload files after you click calculate and it's not clear as to if they are being included or not in the calculation. 

Environment: Windows, Google Chrome
Steps to Reproduce

- Upload a txt file
- Click calculate
- Click upload a txt file
- Keep repeating until a report is generated
- Only the first txt was processed

**Comment by robertjvardy** [comment]
fixed in: 02a77ee263f8adc4f9184cc697292cd639a42f6d
