### ISSUE TITLE
Should use data-testid instead of data-testId 

### ISSUE THREAD

**Issue by Gabriel-Gebril** [myrithok/James#49]
When testing it seems data-testId was used as a field which makes it appear in the dom. This causes performance issues on load for low power devices because react feels the need to print the warning with ever single function. A one character typo made my sad Chromebook whurr.

Environment:
Windows, Google Chrome

Steps to Reproduce

- Upload a txt file
- Wait for calculation
- On the calculated page this warning will pop up

**Comment by Gabriel-Gebril** [comment]
![image](https://user-images.githubusercontent.com/16761051/110030869-36f06f00-7d04-11eb-894d-bd9db0e78f69.png)
I'll save the rest of the screenshot, it's another 1000 react functions.

**Comment by Gabriel-Gebril** [comment]
Environment:
Windows, Google Chrome

Steps to Reproduce

- Upload a txt file
- Wait for calculation
- On the calculated page this warning will pop up

**Comment by myrithok** [comment]
Thank you! Fixed in commit dc17c25125b0eb126102944fcf121e98d590b94c
