### ISSUE TITLE
Algorithm struggles with first topic when the main point isn't in the text.

### ISSUE THREAD

**Issue by Gabriel-Gebril** [myrithok/James#50]
[emp.txt](https://github.com/myrithok/James/files/6086698/emp.txt)
Topic 2 correctly finds out that this comment sequence is referring to a rats coat but topic 1 has Ll which is just referring to the the ll in he'll. It's very close though, very impressive.

Environment: Windows, Google Chrome
Steps to Reproduce

- Upload included txt file
- Click calculate
- Wait till report is generated
- Notice that topic 1 shouldn't have Ll (as that isn't sensible) and how the topics in topic 2 should probably be in topic 1

![image](https://user-images.githubusercontent.com/16761051/110032676-6a33fd80-7d06-11eb-8d06-810fbea5ca33.png)

**Comment by myrithok** [comment]
Thank you! The issue with text following apostrophes is fixed in commit 75ed9adaea37c2a47f4afbe4db97aaaa8889e41f
