### ISSUE TITLE
No Denial of Service Guard

### ISSUE THREAD

**Issue by trevorNgo** [myrithok/James#51]
No guard in Flask backend endpoint to protect against Denial of Service attacks in server code to overwhelm system.

Severity: Medium

Reproduction:
Bash+Newman commandline to run parallel instances that run request config from postman collection.

![image](https://user-images.githubusercontent.com/23327878/110152103-4c6ea300-7daf-11eb-8914-0e5f032b3044.png)

**Comment by myrithok** [comment]
Thank you for the feedback! At this time, James is designed as a development level webapp (we are using Flask, after all), but this is certainly something we will want to change and account for when we get to a real production deployment.
