### ISSUE TITLE
App hangs on text file consisting of a single repeated character

### ISSUE THREAD

**Issue by Gregory-Kitching** [myrithok/James#52]
The app fails in a similar way to issues #19 and #20. File consisted of 259 "A"s on a single line.

It seems there is some minimum file complexity required for the app to work.

![Screenshot from 2021-03-05 13-04-58](https://user-images.githubusercontent.com/79662360/110155289-6ad69d80-7db3-11eb-8752-9559f930ae45.png)

**Comment by eaharis** [comment]
Fixed: 77e18121a7ebf7c177b03443a12ecd95cc07ebc5
