### ISSUE TITLE
Dropzone component allows for uploading non .txt files

### ISSUE THREAD

**Issue by syed-razi** [myrithok/James#53]
### Description:
While looking through your react component that allows for uploading files, I noticed that there was no prevention for uploading non txt files even though the react component you used, Dropzone, provides a prop to do so

### Environment:
Device: Macbook Pro 2015
Browser: Chrome

### Steps to Reproduce:
1. Click "Drop files..." button
2. upload any non .txt file

### Actual Result:

This is what I see when I upload a file with the `*.md` extension

![image](https://user-images.githubusercontent.com/25377291/110192806-6e434680-7dfe-11eb-8dfe-8e6e81aeb0d2.png)

### Expected Result:

I should however see something which more closely resembles this:

![image](https://user-images.githubusercontent.com/25377291/110192836-9d59b800-7dfe-11eb-8923-cabd485087e2.png)

I took this image when trying to upload a `*.md` file to a drag 'n' drop area which only accepts `*.jpeg` and `*.png` files. Link to the section of the react-dropzone docs which allows for drag 'n' drop of only `*.jpeg` and `*.png` files [here](https://react-dropzone.js.org/#section-accepting-specific-file-types)

### Suggestion:

You can add the `accept` prop to your  Dropzone component (see [here](https://react-dropzone.js.org/#src))

**Comment by robertjvardy** [comment]
fixed by: 5336d88cb432f0e32eaeb4db59cababf63e1c657
