### ISSUE TITLE
File numbering starts at 0, expected 1

### ISSUE THREAD

**Issue by syed-razi** [myrithok/James#54]
### Description:
When uploading a file, I noticed that the file numbering starts at 0, though intuitively it would make sense for the first file uploaded to be labeled 'File 1'

### Environment:
Device: Macbook Pro 2015
Browser: Chrome

### Steps to Reproduce:
1. Click "Drop files..." button
2. Upload any file

### Actual Result:

When uploading a file, I see `File 0` as the label:

![image](https://user-images.githubusercontent.com/25377291/110192806-6e434680-7dfe-11eb-8dfe-8e6e81aeb0d2.png)

### Expected Result:

I should see `File 1` as the label

### Suggestion:

You can simply change the numbering to start from 1 and this should resolve the issue

**Comment by myrithok** [comment]
Thank you! Fixed in commit 5ef41c6197c3b8759e29b0d0f06d996403f41449
