### ISSUE TITLE
Get Request Returns Last Computed Result

### ISSUE THREAD

**Issue by trevorNgo** [myrithok/James#55]
There should not be a way for anyone to view the latest results given to another user. If some user sent a text doc with sensitive/personal or government information to be computed, an attacker can easily use this endpoint to view all keywords of that text.

![image](https://user-images.githubusercontent.com/23327878/110215540-5f00df00-7e78-11eb-8fc8-c8a9eede7a1a.png)

There should not be a GET endpoint open to retrieve the latest computed result **if it is not** protected by Authentication+Authorization service:
https://github.com/myrithok/James/blob/32ba2d125cd6dbef17a3de7f7a241e8ca8647ea2/api/server.py#L57
I don't imagine there is a requirement for maintaining access control so this endpoint should not exist.

Severity Medium

Reproduction:
Use postman 
Launch GET request to the backend service located at `http://35.183.97.235:8002/upload` to view results of last successful computed corpus.

**Comment by myrithok** [comment]
Thank you! Fixed in commit 7c77e86fbb0c9e6e2e838461f50dd78832be5477
