### ISSUE TITLE
Foreign words are analyzed

### ISSUE THREAD

**Issue by yangy113** [myrithok/James#56]
[1.txt](https://github.com/myrithok/James/files/6095923/1.txt)

Design Document says "Only English documents uploaded by the user will work with the software" in `2.2.1 Data Representation`. However, many English documents also contain a few non-English words used for quoting or explaining something. The text file `1.txt` was abstracted from English Wikipedia, introducing an ancient Chinese general. The link is [https://en.wikipedia.org/wiki/Yue_Fei#Martial_arts](url). 

In `James`, some Chinese words are analyzed and outputted as well. In this case, lack the function of recognizing this foreign language, the characters `James` caught in `1.txt` were not even a real word in Chinese. 

  
![image](https://user-images.githubusercontent.com/70185196/110218441-c3618400-7ef4-11eb-9a4d-8b2bcc2703bb.png)

I think this issue can be solved by banning `James` to analyze characters other than those used in English.

**Comment by myrithok** [comment]
Thank you for the feedback! While restricting input containing characters not used in English would prevent input of some non-English languages, it certainly would not prevent all of them. In the end, we've decided to add a warning to the instructions on the page that clearly states that behaviour in any language other than English is unsupported. These instructions were added in commit 00267355b8d719f8c699641861c2a13ecda95c08
