### ISSUE TITLE
Contraction Words Not Handled Correctly

### ISSUE THREAD

**Issue by syed-razi** [myrithok/James#58]
### Description:
I noticed that when uploading a txt file that includes contractions, words are not converted "to their standard" lexicon as per functional requirement 3-2-6

### Environment:
Device: Macbook Pro 2015
Browser: Chrome

### Steps to Reproduce:
1. Click "Drop files..." button
2. Upload the following file:  [Test.txt](https://github.com/myrithok/James/files/6096023/Test.txt)

### Actual Result:

When uploading the above file I see:

![image](https://user-images.githubusercontent.com/25377291/110219634-74810380-7e8e-11eb-8ed8-bbb36ccf7ec0.png)

### Expected Result:

I would expect to see the contractions correctly converted to their base components. For example, for a word like "wouldn't" I would expect to see "would" and  "not"

**Comment by Warbler-tweet** [comment]
We removed requirement 3-2-6. The design is to keep words in their stem form, even when contracted.
