### ISSUE TITLE
Inconvenient Result Page Design

### ISSUE THREAD

**Issue by yangy113** [myrithok/James#59]
![image](https://user-images.githubusercontent.com/70185196/110219780-302c4c80-7efc-11eb-9610-e66344fef765.png)

The 19 topics of uploaded file were all displayed on one result page, which makes the user has to scroll down to bottom. Actually, the size of the file is only 5,382 bytes, which means the user would scroll their mouse all along the long page to the bottom can he/she find the `Reset` button if there is a much longer file. 

I think paging the result page is the best solution. Of course, it can also make sense to add another `Reset` button at the top of the result page.

**Comment by myrithok** [comment]
Thank you for your feedback; this is a great suggestion! We've moved the reset button (and the newer download button) to the top of the page, and implemented a "Back to Top" button in commit 5aeddd60a9d1777836cef1f29d33bac8d0627d5a
