### ISSUE TITLE
Number of Topics allows the input of abnormal values

### ISSUE THREAD

**Issue by yangy113** [myrithok/James#60]
It can be seen from Issues #14 #15 #21 and #25  that `Number of Topics` bar allows the input of enormous numbers, zero, negative values and float values, which all make the app crash. 

What I found is that, as `-` and `.` are allowed to be inputted, any combination between them and integers is allowed, which leads to a crash.
![image](https://user-images.githubusercontent.com/70185196/110221135-67ebc200-7f05-11eb-8d95-f7a47d55abbc.png)
![image](https://user-images.githubusercontent.com/70185196/110221148-7934ce80-7f05-11eb-827e-88f9eb4a9886.png)
![image](https://user-images.githubusercontent.com/70185196/110221159-8f428f00-7f05-11eb-9ab1-08a43484df9c.png)

**Comment by robertjvardy** [comment]
fixed by:  d0a5bb9540723f17b08cec8ffd258b35a519fa0e
