### ISSUE TITLE
DevTools failed to load SourceMap

### ISSUE THREAD

**Issue by yangy113** [myrithok/James#61]
**Environment**
Windows 10, Google Chrome

**Steps to Repro**

- Upload a txt file
- Wait for calculating
- On the inspect console, this warning appears

![image](https://user-images.githubusercontent.com/70185196/110221597-17299880-7f08-11eb-9413-6b511bd5dfa3.png)

**Comment by myrithok** [comment]
Thank you! Fixed in commit 90c8a03d74b9642f85e09407aec1132192a94b78
