### ISSUE TITLE
Long file names cut off on smaller screens

### ISSUE THREAD

**Issue by syed-razi** [myrithok/James#69]
### Description:
I uploaded a file and noticed that the drop file button remains highlighted for a few seconds after the file has been uploaded. This does not feel like it should be expected.

### Environment:
Device: Macbook Pro 2015
Browser: Chrome

### Steps to Reproduce:
1. Click "Drop files..." button
2. Upload file with long name, like this one: 
[this_is_a_really_really_long_file_name_for_no_reason.txt](https://github.com/myrithok/James/files/6096423/this_is_a_really_really_long_file_name_for_no_reason.txt)

### Actual Result:

file name is cut off:

![image](https://user-images.githubusercontent.com/25377291/110227041-14a45000-7ec2-11eb-84a5-7a644104f661.png)

### Expected Result:

Long file names should be handled gracefully

### Suggestion

Handle either by wrapping the text or using elipses

**Comment by robertjvardy** [comment]
fixed with: 3901c8c6beda7c860d5a83f9ba30ecf926c6dc90
