### ISSUE TITLE
HIGH: Button Text Overflows on Small Screens

### ISSUE THREAD

**Issue by SEsseltine** [myrithok/James#70]
### Bug Description
Button text of the upload button overflows and becomes unreadable on small screens.

**Severity:** HIGH

### Recreation Steps

1. Resize the window horizontally

### Environment
**Browser:** Safari

### Expected Behaviour
Button text should remain fully visible and readable.

### Actual Behaviour 
Part of the button text overflows its container and becomes unreadable.

### Supporting Images
![image](https://user-images.githubusercontent.com/16650214/110249223-2f6ad900-7f43-11eb-997a-0a906a1a7e26.png)

**Comment by robertjvardy** [comment]
fixed with: 3901c8c6beda7c860d5a83f9ba30ecf926c6dc90
