### ISSUE TITLE
MEDIUM: Non-Numeric Text Accepted in Number Topics

### ISSUE THREAD

**Issue by SEsseltine** [myrithok/James#71]
### Bug Description
The (Optional) Number of Topics field accepts non-numeric (text) input.

**Severity:** MEDIUM

### Recreation Steps

1. Click the input box and type text from the keyboard.

### Environment
**Browser:** Safari

### Expected Behaviour
No text should be accepted.

### Actual Behaviour 
Text is accepted in the field.

### Supporting Images
![image](https://user-images.githubusercontent.com/16650214/110249325-a56f4000-7f43-11eb-97a1-e514a2a00394.png)

**Comment by robertjvardy** [comment]
fixed by: d0a5bb9540723f17b08cec8ffd258b35a519fa0e
