### ISSUE TITLE
HIGH: Results Overflow Container

### ISSUE THREAD

**Issue by SEsseltine** [myrithok/James#72]
### Bug Description
The text on the results page overflows its container and parts become invisible or unreadable.

**Severity:** HIGH

### Recreation Steps

1. Upload a text file for analysis
2. Click the Generate button
3. Await results page

### Environment
**Browser:** Safari

### Expected Behaviour
All text should be visible.

### Actual Behaviour 
Text overflows the container and becomes unreadable.

### Supporting Images
![image](https://user-images.githubusercontent.com/16650214/110249675-46aac600-7f45-11eb-9d73-e86f2ae8801b.png)

**Comment by robertjvardy** [comment]
fixed with: 3901c8c6beda7c860d5a83f9ba30ecf926c6dc90
