### ISSUE TITLE
HIGH: Text Overlaps Itself in Table on Results Page

### ISSUE THREAD

**Issue by SEsseltine** [myrithok/James#74]
### Bug Description
The "summary" text in the Sentiments section of the report overlaps and becomes unreadable.

**Severity:** HIGH

### Recreation Steps

1. upload a file
2. Click the Generate button
3. Await results
4. Scroll down to the Sentiments section of the results page

### Environment
**Browser:** Safari

### Expected Behaviour
The text should all be readable

### Actual Behaviour 
The text overlaps and becomes unreadable

### Supporting Images
![image](https://user-images.githubusercontent.com/16650214/110249946-d309b880-7f46-11eb-8a21-25f5bc3e1606.png)

**Comment by robertjvardy** [comment]
fixed with: 3901c8c6beda7c860d5a83f9ba30ecf926c6dc90
