### ISSUE TITLE
MEDIUM: Empty Text File Causes 500

### ISSUE THREAD

**Issue by SEsseltine** [myrithok/James#75]
### Bug Description
Uploading an empty text file causes a 500 server error

**Severity:** HIGH

### Recreation Steps

1. Upload an empty text file
2. Click the Generate button

### Environment
**Browser:** Safari

### Expected Behaviour
A 400 input error and a warning/error message displayed to the user.

### Supporting Images
![image](https://user-images.githubusercontent.com/16650214/110250309-a9ea2780-7f48-11eb-8447-fec7e5a04470.png)

**Comment by eaharis** [comment]
Fixed: c6f512ce1904f804fa096c917e61ad7b505c138d
