### ISSUE TITLE
Entering an arbitrarily high number for number of topics causes the app to hang

### ISSUE THREAD

**Issue by Gregory-Kitching** [myrithok/James#76]
The app hangs when setting an extremely high number of topics.

There should probably be a maximum (and minimum) number that that field will accept - i.e. the frontend won't even send it to the server if the number is out of range.

![Screenshot from 2021-03-07 13-44-18](https://user-images.githubusercontent.com/79662360/110250858-a60bd480-7f4b-11eb-8668-9b59700897df.png)

![Screenshot from 2021-02-25 15-24-00](https://user-images.githubusercontent.com/79662360/110250862-aad08880-7f4b-11eb-8577-23f61742dc8f.png)

**Comment by robertjvardy** [comment]
fixed by: d0a5bb9540723f17b08cec8ffd258b35a519fa0e
