### ISSUE TITLE
HIGH: Single Character File Causes Server 500

### ISSUE THREAD

**Issue by SEsseltine** [myrithok/James#77]
### Bug Description
Uploading a file with a single character causes a 500 server error

**Severity:** HIGH

### Recreation Steps

1. Upload a text file with a single character
2. Click the Generate button

### Environment
**Browser:** Safari

### Expected Behaviour
A 400 input error and a warning/error message displayed to the user.

### Actual Behaviour 
A server 500 is raised and no feedback is provided to the user

### Supporting Images
![image](https://user-images.githubusercontent.com/16650214/110250663-76100180-7f4a-11eb-9b33-49b1a916a0ce.png)

**Comment by eaharis** [comment]
Fixed: c6f512ce1904f804fa096c917e61ad7b505c138d
