### ISSUE TITLE
LOW: Punctuation Biased Results

### ISSUE THREAD

**Issue by SEsseltine** [myrithok/James#78]
### Bug Description
Different punctuation offers different results. When analyzing a file with contents of Fortnite! vs. Fortnite. the results are different and the Fortnite. raises a 500 server error.

**Severity:** LOW

### Recreation Steps

1. Upload test1.txt provided
2. Click the Generate button
3. Reset
4. Upload test2.txt proved
5. Click the Generate button
6. Receive 500 error in the console

### Environment
**Browser:** Safari

### Expected Behaviour
The same outcome should be received for each file.

### Actual Behaviour 
A different outcome is received for each file.

### Supporting Images
![image](https://user-images.githubusercontent.com/16650214/110251392-38ad7300-7f4e-11eb-9246-60addc0b54b9.png)
![image](https://user-images.githubusercontent.com/16650214/110251428-5bd82280-7f4e-11eb-8b04-76e556aeb97e.png)

### Tested Files
[test2.txt](https://github.com/myrithok/James/files/6097784/test2.txt)
[test1.txt](https://github.com/myrithok/James/files/6097785/test1.txt)

**Comment by myrithok** [comment]
Thank you! This issue was actually arising because the input is too short. We've added instructions regarding input length, and correctly handled errors when input is too short.
