### ISSUE TITLE
MEDIUM: Setting Number of Topics Greater than Identifiable Topics Causes 500

### ISSUE THREAD

**Issue by SEsseltine** [myrithok/James#79]
### Bug Description
When attempting to analyze a file, if a greater Number of Topics is input than can be found in the document, a server 500 error is raised.

**Severity:** MEDIUM

### Recreation Steps

1. Upload the provided test1.txt file
2. Set the Number of Topics field to 2
3. Click the Calculate button

### Environment
**Browser:** Google Chrome

### Expected Behaviour
An error is raised to the user or the file is processed without the optional Number of Topics field.

### Actual Behaviour 
A server 500 error is raised

### Supporting Images
![image](https://user-images.githubusercontent.com/16650214/110251669-8ecee600-7f4f-11eb-91b7-9a7c6f1b44a4.png)

### Testing Files
[test1.txt](https://github.com/myrithok/James/files/6097793/test1.txt)

**Comment by eaharis** [comment]
Fixed by : 77e18121a7ebf7c177b03443a12ecd95cc07ebc5
