### ISSUE TITLE
previous page prevention

### ISSUE THREAD

**Issue by Danielwu9226** [myrithok/James#81]
If the page is calculating, there must be alerts to allow the user to prevent from going back and forth of the webpage, this will prevent data loss and doing tedious recalculating. 

Severenity: minor

**Comment by myrithok** [comment]
Thank you for your feedback! We don't want our web app to produce any popups at all, but we have added some clarifying text and a cancel button while processing in this commit 009e635985ece91dc538b10197fefce81efc2e7b, and will update the instructions in the webapp description soon.
