### ISSUE TITLE
backward prevention

### ISSUE THREAD

**Issue by Danielwu9226** [myrithok/James#83]
After the data is loaded with the data analyzed, alert user if they go to previous page, because the process is relatively slow, recalculating is extremely time consuming.

Severenity: High

**Comment by myrithok** [comment]
Thank you for the feedback! While we have deliberately designed our webapp to not make use of any popups whatsoever, we have added a clear warning to the instructions that results will be lost once the page is left. This warning was added in commit 00267355b8d719f8c699641861c2a13ecda95c08
