### ISSUE TITLE
Allows Me To Paste Non-number Characters Into Number Of Topics (On PC)

### ISSUE THREAD

**Issue by Matthew-Sordo** [myrithok/James#84]
### Severity

High

### Environment

Windows 10 Google Chrome 

### Steps to reproduce:

1. Go to the site.
2. Upload Text file.
3. Go to some text on your computer and copy it. 
4. Paste it into the number of topics box. 

### Expected:

Should not allow me to do this since it is meant to only take numbers as input. It won't let me type letters like this. 

### Actual:

It allows me to paste in letters. This causes a crash that doesn't allow the software to move forward. 

### Screenshot:
<img width="494" alt="char1" src="https://user-images.githubusercontent.com/80217306/110297201-39332180-7fc1-11eb-8cb9-8bef4519692b.PNG">

<img width="483" alt="char" src="https://user-images.githubusercontent.com/80217306/110297059-0e48cd80-7fc1-11eb-8d64-c78da2dff247.PNG">

**Comment by robertjvardy** [comment]
fixed by: d0a5bb9540723f17b08cec8ffd258b35a519fa0e
