### ISSUE TITLE
Landscape On Mobile Adds Whitespace (Looks Clunky)

### ISSUE THREAD

**Issue by Matthew-Sordo** [myrithok/James#85]
### Severity

Minimum 

### Environment

Apple OS, Safari,  IPhone 11

### Steps to reproduce:

1. Go to site.
2. Rotate phone or tablet to landscape mode. 

### Expected:

It should look clean and the outside should be grayed out just as it is when displayed vertically. 

### Actual:

The grey background ends and a white space is displayed. This is a minor aesthetic issue if someone chooses to access this from their phone or tablet. 

### Screenshot:
![IMG_1875](https://user-images.githubusercontent.com/80217306/110299071-47823d00-7fc3-11eb-8b18-8499bc4ecbc0.jpeg)

**Comment by robertjvardy** [comment]
fixed by: 3901c8c6beda7c860d5a83f9ba30ecf926c6dc90
