### ISSUE TITLE
Dropbox Allows Photos To be Taken and Analyzed on Mobile and Then Stuck In Infinite Loop

### ISSUE THREAD

**Issue by Matthew-Sordo** [myrithok/James#86]
### Severity

High

### Environment

Apple OS, Safari,  IPhone 11

### Steps to reproduce:

1. Go to site.
2. Click drop box button.
3. Choose the take photo option. 
4. Take photo and upload it.
3. Try analyzing it. 

### Expected:

The option to take a picture and upload it for an application like this should be blocked. 

### Actual:

The program allows the photo to be taken and accepts it as if it were text. This is a very big issue if someone chooses to access this from their phone or tablet. 

### Screenshot:
![IMG_1870](https://user-images.githubusercontent.com/80217306/110299181-608aee00-7fc3-11eb-8c45-c798be026780.jpeg)
![IMG_1872](https://user-images.githubusercontent.com/80217306/110299197-6385de80-7fc3-11eb-8d3b-e748ee1ea5c0.jpeg)

**Comment by robertjvardy** [comment]
fixed by: 5336d88cb432f0e32eaeb4db59cababf63e1c657
