### ISSUE TITLE
Non-number Characters Can be Entered Into Number of Topics Text field If On Mobile Device 

### ISSUE THREAD

**Issue by Matthew-Sordo** [myrithok/James#87]
### Severity

High

### Environment

Apple OS, Safari,  IPhone 11

### Steps to reproduce:

1. Go to site.
2. Click Number of Topic text field. 
3. Type whatever you want using the phone keyboard

### Expected:

The option to do this with non number characters should be blocked. 

### Actual:

I was able to type whatever I wanted. This is a very big issue if someone chooses to access this from their phone or tablet. 

### Screenshot:
![IMG_1874](https://user-images.githubusercontent.com/80217306/110299297-80221680-7fc3-11eb-91f3-f9fc63cb11d8.jpeg)

**Comment by robertjvardy** [comment]
fixed by: d0a5bb9540723f17b08cec8ffd258b35a519fa0e
