### ISSUE TITLE
Significant spelling errors on the homepage

### ISSUE THREAD

**Issue by leon1213** [myrithok/James#88]
![image](https://user-images.githubusercontent.com/48035126/110307194-9a96d700-8039-11eb-89e0-37839e387f69.png)
`Help up improve` should be `Help Us Improve`.

**Comment by myrithok** [comment]
Thank you! Corrected typo in commit 6346602d222de041462fe53f87f91ceb740205b1, and corrected capitalization in commit 59417a612a254329495ccf7b0f6575bff3775a82
