### ISSUE TITLE
Zero values listed in the topic analysis

### ISSUE THREAD

**Issue by leon1213** [myrithok/James#89]
![image](https://user-images.githubusercontent.com/48035126/110308076-a0d98300-803a-11eb-900a-d1e7cd83e0f1.png)

The user (such as me) is not sure why these zero values are listed. Is that an error? Or they are listed reasonably? This issue should be explained.

**Comment by myrithok** [comment]
Thank you! Fixed in commit c4bb1537096f9dba16ed67c916bedff2b09edf67
