### ISSUE TITLE
Weight and sentiment same for all topics on file that fails on its own

### ISSUE THREAD

**Issue by BryanChiu** [myrithok/James#92]
Severity: Medium

OS: Windows 10 Home
Browser: Chrome 89.0.4389.82

Description: When processing files that normally fail on their own with files that "work", the weight for each topic is the same (1/# of topics) and sentiment is 0.0.
![image](https://user-images.githubusercontent.com/25440765/110314031-52de6400-7fd5-11eb-9d59-9d6c7da5dc70.png)
In the example above, `cat.txt` fails when uploaded on its own (`Error: Request failed with status code 500`). However, we get the above when uploaded along with `bat.txt`,

**Comment by myrithok** [comment]
Thank you! We are now handling errors correctly, and input should no longer process if any of the input files cannot process correctly.
